<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Configuracoes\Module'                        => __DIR__ . '/Module.php',
    'Configuracoes\Controller\ConfiguracoesController' => __DIR__ . '/src/Configuracoes/Controller/ConfiguracoesController.php',
    'ConfiguracoesTest\Framework\TestCase'        => __DIR__ . '/tests/Configuracoes/Framework/TestCase.php',
    'ConfiguracoesTest\SampleTest'                => __DIR__ . '/tests/Configuracoes/SampleTest.php',
);
