<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tomadas\Module'                        => __DIR__ . '/Module.php',
    'Tomadas\Controller\TomadasController' => __DIR__ . '/src/Tomadas/Controller/TomadasController.php',
    'TomadasTest\Framework\TestCase'        => __DIR__ . '/tests/Tomadas/Framework/TestCase.php',
    'TomadasTest\SampleTest'                => __DIR__ . '/tests/Tomadas/SampleTest.php',
);
