<?php
$login = 'Login EasyT';
$this->headTitle($login);
?>

<?php
$usuario = $loginForm->get('usuario');
$usuario->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);
#$usuario->setAttribute('placeholder', 'Usuario');

$senha = $loginForm->get('senha');
$senha->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);
#$senha->setAttribute('placeholder', 'Senha');

$submit = $loginForm->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$loginForm->setAttribute('action', $this->url('login'));
$loginForm->prepare();
?>

<div class="col-md-4 " style="background: #c9e2b3; padding-top: 35px; border-radius: 20px; margin-left: 25%">
    <div class="login">
        <div class="text-center">
        <img class="text-center" src="<?= $this->basePath('img/logo_easyt.png') ?>" height="50"
             alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
        </div>
        <?php echo $this->form()->openTag($loginForm); ?>

        <hr>
        <?php if ($messageError): ?>
            <div class="alert alert-danger alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <strong>Erro!</strong><?= $messageError ?>
            </div>
        <?php endif; ?>

        <p class="text-muted text-center">Insira seus dados para
            autenticação</p>

        <?php $message = $this->formElementErrors()->render($usuario, ['class' => 'help-block'])?>
        <div class="form-group">
            <?= $this->formLabel($usuario) ?>
            <?= $this->formElement($usuario) ?>
            <?= $this->formElementErrors()->render($usuario, ['class' => 'help-block']) ?>
        </div>

        <?php $message = $this->formElementErrors()->render($senha, ['class' => 'help-block'])?>
        <div class="form-group">
            <?= $this->formLabel($senha) ?>
            <?= $this->formElement($senha) ?>
            <?= $this->formElementErrors()->render($senha, ['class' => 'help-block']) ?>
        </div>


        <?php
        echo $this->formSubmit($submit);
        echo $this->form()->closeTag();
        ?>

    </div>

    <hr>
    <p class="text-muted text-right">
        Made by <span style="font-weight: bold;">EasyTech®</span>
</div>

