<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">

            <div class="container">

                <div class="page-header">
                    <h1>Relatórios</h1>
                </div>

                <div class="row">
                    <div class="col-xs-8">
                        <form class="form-horizontal">

                            <div class="form-group">
                                <label class="control-label col-lg-4" for="datainicial">Data
                                    Inicial</label>

                                <div class="col-lg-3">
                                    <input type="text" class="form-control" value="DD-MM-AAAA"
                                           id="datainicial">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4" for="datafinal">Data
                                    Final</label>

                                <div class="col-lg-3">
                                    <input type="text" class="form-control" value="DD-MM-AAAA"
                                           id="datafinal">
                                </div>
                            </div>

                            <label class="control-label col-lg-4">Selecione a saída
                                desejada:</label>
                            <div class="col-lg-3">
                                <select class="form-control">
                                    <option>Todos</option>
                                    <option>Saída01</option>
                                    <option>Saída02</option>
                                    <option>Saída03</option>
                                    <option>Saída04</option>
                                    <option>Saída06</option>
                                    <option>Saída07</option>
                                    <option>Saída08</option>
                                </select>
                            </div>

                        </form>
                    </div>
                </div>

                <div class="row form-horizontal list-inline">
                    <div class="" id="relatorios">
                        <div class="col-xs-6">
                            <div class="btn">
                                <img src="<?= $this->basePath('img/consumoicon.png') ?>" class="img-responsive"
                                     width="80px"/>
                            </div>
                            <div class="btn">
                                <img src="<?= $this->basePath('img/gastosicon.png') ?>" class="img-responsive"
                                     width="80px"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
</div>
