<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Agenda\Module'                        => __DIR__ . '/Module.php',
    'Agenda\Controller\AgendaController' => __DIR__ . '/src/Agenda/Controller/AgendaController.php',
    'AgendaTest\Framework\TestCase'        => __DIR__ . '/tests/Agenda/Framework/TestCase.php',
    'AgendaTest\SampleTest'                => __DIR__ . '/tests/Agenda/SampleTest.php',
);
