<?php
$usuario = 'Add novo usuario';
$this->headTitle($usuario);
?>
    <h1><?= $this->escapeHtml($usuario) ?></h1>
<?php
$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control');
$nome->setAttribute('placeholder', 'Nome');

$usuario = $form->get('usuario');
$usuario->setAttribute('class', 'form-control');
$usuario->setAttribute('placeholder', 'Usuario');

$senha = $form->get('senha');
$senha->setAttribute('class', 'form-control');
$senha->setAttribute('placeholder', 'Senha');


$idpermissao = $form->get('idpermissao');
$idpermissao->setAttribute('class', 'form-control');
$idpermissao->setAttribute('placeholder', 'Idpermissao');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('configuracoes', ['action' => 'adduser']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php $message = $this->formElementErrors()->render($nome, ['class' => 'help-block'])?>
    <div class="form-group<?= $message ?" has-error": ""?>">
        <?= $this->formElement($nome); ?>
        <?= $message ?>
    </div>

<?php $message = $this->formElementErrors()->render($usuario, ['class' => 'help-block'])?>
    <div class="form-group<?= $message ?" has-error": ""?>">
        <?= $this->formElement($usuario) ?>
        <?= $message ?>
    </div>

    <div class="form-group<?= $message ?" has-error": ""?>">
        <?= $this->formElement($senha) ?>
        <?= $this->formElementErrors()->render($senha, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group<?= $message ?" has-error": ""?>">
        <?= $this->formElement($idpermissao) ?>
        <?= $this->formElementErrors()->render($idpermissao, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
