<?php $this->headTitle("Configurações"); ?>
<style>
    .row-clicked {
        background-color: red;
    }


    /*td {border: 1px #761c19 solid; padding: 5px; cursor: pointer;}*/

    .selected {
        background-color: #ce8483;
        color: #761c19;
    }
</style>


<div class="container row" xmlns:cursor="http://www.w3.org/1999/xhtml">
    <div class="col-lg-8">
        <div class="box dark">
            <header>
                <div clas="icons"><i class="fa fa-edit"</i></div>
                <h3>Configurações</h3>
            </header>
            <div id="corpo" class="body">
                <form class="form-horizontal">
                    <!-- Categoria Rede -->
                    <h4>Rede</h4>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input class="uniform" type="checkbox" value="option1" checked>
                                Obter endereço IP Automaticamente.
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="ip" class="control-label col-lg-4">Endereço IP</label>
                        <div class="col-lg-8">
                            <input type="text" id="ip" placeholder="192.168.0.2" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="mask" class="control-label col-lg-4">Máscara de Rede</label>
                        <div class="col-lg-8">
                            <input type="text" id="mask" placeholder="255.255.0.0" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="gateway" class="control-label col-lg-4">Gateway</label>
                        <div class="col-lg-8">
                            <input type="text" id="gateway" placeholder="192.168.0.1" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="dns" class="control-label col-lg-4">Servidor DNS</label>
                        <div class="col-lg-8">
                            <input type="text" id="dns" placeholder="8.8.8.8" class="form-control">
                        </div>
                    </div>


                    <!-- Categoria WiFi -->
                    <h4>Rede Wirelles</h4>
                    <div class="form-group">
                        <div class="checkbox">
                            <label class="switch"> <input type="checkbox">
                                <span class="slider round"></span>
                            </label> Ativar rede Wireless
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ssid" class="control-label col-lg-4">SSID</label>
                        <div class="col-lg-8">
                            <input type="text" id="ssid" placeholder="Insira o nome de sua rede Wifi"
                                   class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ssid" class="control-label col-lg-4">Senha</label>
                        <div class="col-lg-8">
                            <input type="password" id="tarifa"
                                   placeholder="Insira sua senha" class="form-control">
                        </div>
                    </div>


                    <!-- Categoria Consumo -->

                    <h4>Consumo</h4>
                    <div id="consumo" class="form-group">
                        <label for="tarifa" class="control-label col-lg-4">Tarifa R$</label>
                        <div class="col-lg-8">
                            <input type="text" id="tarifa"
                                   placeholder="Insira a tarifa de energia de seu estado"
                                   class="form-control">
                        </div>
                    </div>


                    <!-- Categoria Acesso -->
                    <h4>Acesso</h4>
                    <div id="acesso" class="form-group">
                        <div class="checkbox">
                            <label> <input class="uniform" type="checkbox"
                                           value="option1" checked> Habilitar serviço SSH na porta 22
                            </label>
                        </div>
                    </div>

                    <!-- Categoria para os usuários -->


                    <h4>Usuários</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="box">
                                <header>
                                    <div class="btn-group pull-right">
                                        <a href="javascript:addPopup()" class="btn btn-sm btn-default">
                                            Adicionar
                                            <i class="glyphicon glyphicon-plus"></i>
                                        </a>
                                        <a href="javascript:edtPopup()" class="btn btn-sm btn-default">
                                            Editar
                                            <i class="glyphicon glyphicon-pencil"></i>
                                        </a>
                                        <a href="javascript:delUser()" class="btn btn-sm btn-default">
                                            Excluir
                                            <i class="glyphicon glyphicon-trash"></i>
                                        </a>
                                    </div>
                                </header>
                                <div id="collapse4" class="body">
                                    <table id="dataTable"
                                           class="table table-bordered table-condensed table-hover table-striped">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nome</th>
                                            <th>Usuário</th>
                                            <th>Permissão</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($usuarios as $usuario): ?>
                                            <tr class="";
                                                onclick='Marque("<?= $this->escapeHtml($usuario->id); ?>")'
                                                style="cursor:pointer">
                                                <td><?= $this->escapeHtml($usuario->id); ?></td>
                                                <td><?= $this->escapeHtml($usuario->nome); ?></td>
                                                <td><?= $this->escapeHtml($usuario->usuario); ?></td>
                                                <td><?= $this->escapeHtml($usuario->idpermissao); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <!--Botões de salvar e cancelar-->
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="body collapse in" id="div1">
                                    <a href="#" class="btn btn-success">Salvar</a> <a href="#"
                                                                                      class="btn btn-danger">Descartar</a>
                                </div>
                            </div>
                        </div>
                </form>
            </div>
        </div>
    </div>


</div>
</div>


</div>
<!-- /#page-content-wrapper -->
</div>

<Script language=javascript type="text/javascript">

    var value;

    $("#dataTable tr").click(function(){
        $(this).addClass('selected').siblings().removeClass('selected');
        value=$(this).find('td:first').html();
        //alert(value);

    });
    $('.ok').on('click', function(e){
        alert($("#dataTable tr.selected td:first").html());
    });

    function addPopup() {
        varWindow = window.open('configuracoes/adduser', "", "width=450,height=650");
    }

    function Marque(id) {
        var id = id;
    }

    function edtPopup() {
        if(value==null){
            alert('Selecione o item antes de editar!!');
        } else {
            varWindow = window.open('configuracoes/edtuser/'+value, "", "width=450,height=650");
        }
    }

    function delUser() {

        if(value==null){
            alert('Selecione o item antes de excluir!!');
        } else {
            decisao = confirm("Tem certeza que deseja excluir o usuário?");
            if(decisao) {
                window.location='configuracoes/deleteUser/'+value;
                alert('Dado deletado com sucesso!');
            } else {
            }
        }
    }

</Script>
<hr>