<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Relatorios\Module'                        => __DIR__ . '/Module.php',
    'Relatorios\Controller\RelatoriosController' => __DIR__ . '/src/Relatorios/Controller/RelatoriosController.php',
    'RelatoriosTest\Framework\TestCase'        => __DIR__ . '/tests/Relatorios/Framework/TestCase.php',
    'RelatoriosTest\SampleTest'                => __DIR__ . '/tests/Relatorios/SampleTest.php',
);
